<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VinApartmentType', 'doctrine');

/**
 * BaseVinApartmentType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $vin_key
 * @property string $name_type
 * @property string $featured_image
 * @property string $standard_transfer_file
 * @property string $ground_apartment_file
 * @property string $bad_room
 * @property string $bath_room
 * @property string $kitchen_room
 * @property string $balcony
 * @property string $description
 * @property string $heart_wall
 * @property string $clear_span
 * @property string $vin_model
 * @property string $parent_type
 * @property integer $apartment_cat
 * @property integer $priority
 * 
 * @method string           getVinKey()                 Returns the current record's "vin_key" value
 * @method string           getNameType()               Returns the current record's "name_type" value
 * @method string           getFeaturedImage()          Returns the current record's "featured_image" value
 * @method string           getStandardTransferFile()   Returns the current record's "standard_transfer_file" value
 * @method string           getGroundApartmentFile()    Returns the current record's "ground_apartment_file" value
 * @method string           getBadRoom()                Returns the current record's "bad_room" value
 * @method string           getBathRoom()               Returns the current record's "bath_room" value
 * @method string           getKitchenRoom()            Returns the current record's "kitchen_room" value
 * @method string           getBalcony()                Returns the current record's "balcony" value
 * @method string           getDescription()            Returns the current record's "description" value
 * @method string           getHeartWall()              Returns the current record's "heart_wall" value
 * @method string           getClearSpan()              Returns the current record's "clear_span" value
 * @method string           getVinModel()               Returns the current record's "vin_model" value
 * @method string           getParentType()             Returns the current record's "parent_type" value
 * @method integer          getApartmentCat()           Returns the current record's "apartment_cat" value
 * @method integer          getPriority()               Returns the current record's "priority" value
 * @method VinApartmentType setVinKey()                 Sets the current record's "vin_key" value
 * @method VinApartmentType setNameType()               Sets the current record's "name_type" value
 * @method VinApartmentType setFeaturedImage()          Sets the current record's "featured_image" value
 * @method VinApartmentType setStandardTransferFile()   Sets the current record's "standard_transfer_file" value
 * @method VinApartmentType setGroundApartmentFile()    Sets the current record's "ground_apartment_file" value
 * @method VinApartmentType setBadRoom()                Sets the current record's "bad_room" value
 * @method VinApartmentType setBathRoom()               Sets the current record's "bath_room" value
 * @method VinApartmentType setKitchenRoom()            Sets the current record's "kitchen_room" value
 * @method VinApartmentType setBalcony()                Sets the current record's "balcony" value
 * @method VinApartmentType setDescription()            Sets the current record's "description" value
 * @method VinApartmentType setHeartWall()              Sets the current record's "heart_wall" value
 * @method VinApartmentType setClearSpan()              Sets the current record's "clear_span" value
 * @method VinApartmentType setVinModel()               Sets the current record's "vin_model" value
 * @method VinApartmentType setParentType()             Sets the current record's "parent_type" value
 * @method VinApartmentType setApartmentCat()           Sets the current record's "apartment_cat" value
 * @method VinApartmentType setPriority()               Sets the current record's "priority" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVinApartmentType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vin_apartment_type');
        $this->hasColumn('vin_key', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'ma',
             'length' => 255,
             ));
        $this->hasColumn('name_type', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'name',
             'length' => 255,
             ));
        $this->hasColumn('featured_image', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'model',
             'length' => 255,
             ));
        $this->hasColumn('standard_transfer_file', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'model',
             'length' => 255,
             ));
        $this->hasColumn('ground_apartment_file', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'model',
             'length' => 255,
             ));
        $this->hasColumn('bad_room', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'model',
             'length' => 255,
             ));
        $this->hasColumn('bath_room', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'model',
             'length' => 255,
             ));
        $this->hasColumn('kitchen_room', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'model',
             'length' => 255,
             ));
        $this->hasColumn('balcony', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'model',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'model',
             'length' => 255,
             ));
        $this->hasColumn('heart_wall', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'model',
             'length' => 255,
             ));
        $this->hasColumn('clear_span', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'model',
             'length' => 255,
             ));
        $this->hasColumn('vin_model', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'model',
             'length' => 255,
             ));
        $this->hasColumn('parent_type', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'model',
             'length' => 255,
             ));
        $this->hasColumn('apartment_cat', 'integer', 22, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => 'model',
             'length' => 22,
             ));
        $this->hasColumn('priority', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => 'model',
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}