<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VinBuildingType', 'doctrine');

/**
 * BaseVinBuildingType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $vin_key
 * @property string $name
 * @property string $clear_span
 * @property string $heart_wall
 * @property string $image
 * @property string $type
 * @property integer $apartment_type_id
 * @property integer $apartment_cat
 * 
 * @method string          getVinKey()            Returns the current record's "vin_key" value
 * @method string          getName()              Returns the current record's "name" value
 * @method string          getClearSpan()         Returns the current record's "clear_span" value
 * @method string          getHeartWall()         Returns the current record's "heart_wall" value
 * @method string          getImage()             Returns the current record's "image" value
 * @method string          getType()              Returns the current record's "type" value
 * @method integer         getApartmentTypeId()   Returns the current record's "apartment_type_id" value
 * @method integer         getApartmentCat()      Returns the current record's "apartment_cat" value
 * @method VinBuildingType setVinKey()            Sets the current record's "vin_key" value
 * @method VinBuildingType setName()              Sets the current record's "name" value
 * @method VinBuildingType setClearSpan()         Sets the current record's "clear_span" value
 * @method VinBuildingType setHeartWall()         Sets the current record's "heart_wall" value
 * @method VinBuildingType setImage()             Sets the current record's "image" value
 * @method VinBuildingType setType()              Sets the current record's "type" value
 * @method VinBuildingType setApartmentTypeId()   Sets the current record's "apartment_type_id" value
 * @method VinBuildingType setApartmentCat()      Sets the current record's "apartment_cat" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVinBuildingType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vin_building_type');
        $this->hasColumn('vin_key', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'code,key',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'name',
             'length' => 255,
             ));
        $this->hasColumn('clear_span', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'ApartmentCategory, floorsCategory',
             'length' => 255,
             ));
        $this->hasColumn('heart_wall', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'ApartmentCategory, floorsCategory',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'ApartmentCategory, floorsCategory',
             'length' => 255,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'model',
             'length' => 255,
             ));
        $this->hasColumn('apartment_type_id', 'integer', 22, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => 'model',
             'length' => 22,
             ));
        $this->hasColumn('apartment_cat', 'integer', 22, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => 'model',
             'length' => 22,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}