<?php

/**
 * AdPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdPhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdPhoto');
    }
    public static function getPhotoByAlbumId($albumId)
    {
        return AdPhotoTable::getInstance()->createQuery()
            ->select()
            ->where('album_id=?',$albumId)
            ->andwhere('is_active=1');
    }

    public static function getAllPhotos($limit)
    {
        return AdPhotoTable::getInstance()->createQuery()
            ->where('is_active=1')
            ->limit($limit)
            ->fetchArray();
    }
}