<?php

/**
 * VinApartmentTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VinApartmentTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VinApartmentTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VinApartmentType');
    }
}