<?php

/**
 * VinApartmentCate
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VinApartmentCate extends BaseVinApartmentCate
{
    public function getObjApartmentType()
    {
        return VinApartmentTypeTable::getInstance()->getAllApartmentTypeByCat($this->getId());
    }

    public function getVinModelName()
    {
        $arrCat = VinHelper::getVinModel();
        return !empty($arrCat[$this->vin_model]) ? $arrCat[$this->vin_model] : '';
    }

    public function getParentName()
    {
        if ($this->parent && $this->parent != '') {
            $obj = VinApartmentCateTable::getInstance()->findOneById($this->parent);
            return !empty($obj) ? $obj->name : '';
        }
        return "";
    }
}