<?php

/**
 * VinApartmentType
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VinApartmentType extends BaseVinApartmentType
{
    public function getAllImage()
    {
        return VinProductImageTable::getInstance()->getAllImageByApartmentTypeId($this->getId());
    }

    public function getApartmentCatName()
    {
        if ($this->apartment_cat) {
            $obj = VinApartmentCateTable::getInstance()->findOneById($this->apartment_cat);
            return !empty($obj) ? $obj->name : '';
        }
        return '';
    }
}