<?php

/**
 * VinApartmentCateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VinApartmentCateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VinApartmentCateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VinApartmentCate');
    }
}