<?php

/**
 * VinBuildingTypeTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VinBuildingTypeTable extends Doctrine_Table
{
    const isHot = 1;

    /**
     * Returns an instance of this class.
     *
     * @return object VinBuildingTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VinBuildingType');
    }

    public function getListBuildingHot($limit = 5)
    {
        $q = $this->createQuery()
            ->andWhere('is_hot = ?', self::isHot)
            ->limit($limit)
            ->orderBy('name');
        return $q->execute();
    }

    public function getListBuildingByCat($cat, $limit = 5)
    {
        $q = $this->createQuery()
            ->andWhereIn('apartment_cat', $cat)
            ->limit($limit)
            ->orderBy('name');
        return $q->execute();
    }
}