<?php

/**
 * VinBuildingTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VinBuildingTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VinBuildingTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VinBuildingType');
    }
}