<?php

/**
 * VinBuildingType
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VinBuildingType extends BaseVinBuildingType
{
    public function getObjApartmentCat()
    {
        if ($this->getApartmentCat()) {
            return VinApartmentCateTable::getInstance()->findOneBy('id', $this->getApartmentCat());
        }
        return false;
    }

    public function getObjApartmentType()
    {
        if ($this->getApartmentTypeId()) {
            return VinApartmentTypeTable::getInstance()->findOneBy('id', $this->getApartmentTypeId());
        }
        return false;
    }


    public function getApartmentCatName()
    {
        if ($this->apartment_cat) {
            $obj = VinApartmentCateTable::getInstance()->findOneBy('id', $this->apartment_cat);
            return !empty($obj) ? $obj->name : '';
        }
        return '';
    }

    public function getApartmentTypeIdName()
    {
        if ($this->apartment_type_id) {
            $obj = VinApartmentTypeTable::getInstance()->findOneBy('id', $this->apartment_type_id);
            return !empty($obj) ? $obj->name_type : '';
        }
        return '';
    }
}