<?php

/**
 * VinProductImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VinProductImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VinProductImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VinProductImage');
    }
}