# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

#ajax load video
crawNews:
  url: /crawNews
  param: {module: pageHome, action: crawNews}
crawVideo:
  url: /crawVideo
  param: {module: pageHome, action: crawVideo}

getHomeData:
  url: /api/getHomeData
  param: {module: pageHome, action: getHomeData}

getMedia:
  url: /api/getMedia
  param: {module: pageHome, action: getMedia}

order:
  url: /api/order
  param: {module: pageHome, action: order}

introduction:
  url: /introduction
  param: {module: pageHtml, action: introduction}

borrowing:
  url: /borrowing
  param: {module: pageHtml, action: borrowing}

# default rules
homepage:
  url:   /:location
#  param: { module: pageHome, action: index }
  param: { module: pageHome, action: index, location: ''}
  requirements: { sf_method: get }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
